#!/bin/sh
case $1 in
	period-changed)
		case $3 in
			daytime)
				gsettings set org.gnome.desktop.interface color-scheme default
				gsettings reset org.gnome.desktop.interface gtk-theme
				;;
			night)
				gsettings set org.gnome.desktop.interface color-scheme prefer-dark
				gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
				;;
		esac
		;;
esac
